# Generated by Django 3.2.16 on 2022-12-07 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_rawdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 13, 29, 33, 748799)),
        ),
    ]
