# Generated by Django 3.2.16 on 2022-12-07 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_rawdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 16, 2, 10, 312970)),
        ),
    ]
