# Generated by Django 3.2.16 on 2022-12-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_alter_rawdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='date',
        ),
    ]
