# Generated by Django 3.2.16 on 2022-12-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_device_crutch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='crutch',
            field=models.IntegerField(choices=[(0, 'crutch1'), (1, 'crutch2')], default=0),
        ),
    ]
