# Generated by Django 3.2.16 on 2022-12-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_device_crutch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='crutch',
            field=models.CharField(choices=[('https://drive.google.com/uc?id=1Sinfe9CfTtfbeiqH0aiP1oV0JvS62VzM', 'Crutch 1'), ('https://drive.google.com/uc?id=1yVENaWugS-eATe-daysJ2e_TRlbb2rF_', 'Crutch 2')], default=0, max_length=255),
        ),
    ]
